#ifndef VISIONCONSTANTS_H
#define VISIONCONSTANTS_H

#define FRAME_WIDTH 640
#define FRAME_HEIGHT 480

#define RAW_IMAGE_WINDOW_NAME "Raw Image"
#define HSV_IMAGE_WINDOW_NAME "HSV Image"
#define THRESHOLDED_IMAGE_WINDOW_NAME "Thresholded Image"

#define COLOR_MASKS_FILENAME "colormasks.msk"

#define N_COLOR_MASKS 6
enum objectColor {RED=0,ORANGE=1,YELLOW=2,GREEN=3,BLUE=4,VIOLET=5};
#define N_COLOR_MASK_PARAMETERS 7

#define USE_MORPHING_OPERATIONS true
#define MORPH_OPS_ERODE_RECT_SIZE 1
#define MORPH_OPS_DILATE_RECT_SIZE 1

#define RED_MASK_WINDOW_NAME "Red Mask Setup"
#define ORANGE_MASK_WINDOW_NAME "Orange Mask Setup"
#define YELLOW_MASK_WINDOW_NAME "Yellow Mask Setup"
#define GREEN_MASK_WINDOW_NAME "Green Mask Setup"
#define BLUE_MASK_WINDOW_NAME "Blue Mask Setup"
#define VIOLET_MASK_WINDOW_NAME "Violet Mask Setup"

#define DISPLAYED_IMAGE_TRACKBAR_NAME "IMAGE_TYPE"
#define H_MIN_TRACKBAR_NAME "H_MIN"
#define H_MAX_TRACKBAR_NAME "H_MAX"
#define S_MIN_TRACKBAR_NAME "S_MIN"
#define S_MAX_TRACKBAR_NAME "S_MAX"
#define V_MIN_TRACKBAR_NAME "V_MIN"
#define V_MAX_TRACKBAR_NAME "V_MAX"
#define ACTIVE_TRACKBAR_NAME "ACTIVE"

#define MAX_MASK_VALUE 256

#define WAIT_KEY_PRESS_TIME 10
#define DONE_KEY 13

#endif // VISIONCONSTANTS_H
