#ifndef GUICONSTANTS_H
#define GUICONSTANTS_H

#define MAINWINDOW_TITLE "SMMCGUI"

#define INTERPOLATION_METHOD CV_INTER_LANCZOS4

#define SCALAR_RED cv::Scalar(255,0,0)
#define SCALAR_GREEN cv::Scalar(0,255,0)
#define SCALAR_BLUE cv::Scalar(0,0,255)

#define DOT_RADIUS 5
#define DOT_THICKNESS 5

#define DEFAULT_IMAGE_TEXT_FONT CV_FONT_HERSHEY_SIMPLEX
#define IMAGE_TEXT_SCALING 1.0
#define TEXT_OFFSET 10

#define FRAME_REFRESH_RATE_MS 10

#define THREAD_START_WAIT_TIME_US 100
#define THREAD_STOP_WAIT_TIME_US 100
#define MODULES_SHUTDOWN_WAIT_TIME_US 100000

#define RUN_MODULES_INDEX 0
#define GAME_CONTROL_INDEX 1
#define VISION_SETTINGS_INDEX 2
#define AI_SETTINGS_INDEX 3

#endif // GUICONSTANTS_H
