#ifndef GUICONSTANTS_H
#define GUICONSTANTS_H

#define MAINWINDOW_TITLE "SMMCGUI"

#define INTERPOLATION_METHOD CV_INTER_LANCZOS4

#define FRAME_REFRESH_RATE_MS 20

#define THREAD_START_WAIT_TIME_US 100
#define THREAD_STOP_WAIT_TIME_US 100
#define MODULES_SHUTDOWN_WAIT_TIME_US 100000

#define RUN_MODULES_INDEX 0
#define GAME_CONTROL_INDEX 1
#define VISION_SETTINGS_INDEX 2
#define AI_SETTINGS_INDEX 3

#endif // GUICONSTANTS_H
