#ifndef GUICONSTANTS_H
#define GUICONSTANTS_H

#define MAINWINDOW_TITLE "SMMCGUI"

#define INTERPOLATION_METHOD CV_INTER_LANCZOS4 //CV_INTER_CUBIC

#define SCALAR_RED cv::Scalar(0,0,255)
#define SCALAR_GREEN cv::Scalar(0,255,0)
#define SCALAR_BLUE cv::Scalar(255,0,0)

#define DOT_RADIUS 3
#define DOT_THICKNESS 3

#define MOVEMENT_ARROW_LENGTH 130

#define REC_THICKNESS 3

#define DEFAULT_IMAGE_TEXT_FONT CV_FONT_HERSHEY_SIMPLEX
#define IMAGE_TEXT_SCALING 0.97
#define TEXT_X_OFFSET 40
#define TEXT_Y_OFFSET 30

#define FRAME_REFRESH_RATE_MS 10

#define THREAD_START_WAIT_TIME_US 100
#define THREAD_STOP_WAIT_TIME_US 100
#define MODULES_SHUTDOWN_WAIT_TIME_US 300000

#define RUN_MODULES_INDEX 0
#define GAME_CONTROL_INDEX 1
#define VISION_SETTINGS_INDEX 2
#define AI_SETTINGS_INDEX 3

#endif // GUICONSTANTS_H
