#ifndef AICONSTANTS_H
#define AICONSTANTS_H

enum roles {GOALKEEPER = 0, DEFENDER = 1, ATTACKER = 2};

enum modes {ATTACK_MODE = 0, DEFEND_MODE = 1, INTERRUPT_MODE = 2, FREEBALL_MODE = 3};

#define N_MODES 4

#endif //AICONSTANTS_H
