#ifndef AICONSTANTS_H
#define AICONSTANTS_H

enum side {LEFT, RIGHT};

enum roles {ATTACKER, DEFENDER, GOALKEEPER};

enum modes {ATTACK_MODE = 0, DEFEND_MODE = 1, INTERRUPT_MODE = 2, FREEBALL_MODE = 3};

enum {ANTI_CLOCKWISE, CLOCKWISE};

#define SIDE LEFT

#define N_MODES 4

#define MIN_ATTACKING_DIST 200.0
#define OFFSET_X 425.0
#define OFFSET_Y 130.0
#define GOAL_Y 290.0
#define GOAL_X 100.0
#define GOALKEEPER_AREA_Y 450.0
#define GOALKEEPER_AREA_X 130.0
#define SHOOTING_POINT_OFFSET_X 80.0
#define SHOOTING_POINT_RADIUS 90.0

#define INVERT_Y true

#define ANGLE_ORIENTATION CLOCKWISE

#define ANGLE_ADJUSTING false
#define ANGLE_EPISILON 0.05

#define MAX_VELOCITY 0.3
#define MAX_ANG_VELOCITY 5.0*M_PI_2

#define AI_SHARED_MEMORY_NAME "AI"
#define AI_SHARED_MEMORY_SIZE 131072
#define VELOCITIES_MEMORY_NAME "velocities"

#endif //AICONSTANTS_H
